Fix for Travel Advice pages with no summary
A `summary` is no longer required for Travel Advice pages[^1], but if it's not present we currently crash with undefined method `find' for nil:NilClass (NoMethodError).

[^1]: https://github.com/alphagov/publishing-api/commit/21c0711c0a894182ffcd1ed556ac2194e7365c2b