Manually fix remaining linting issues
This multi-statement uses of 'map' with a single call to a private
method. Note that, while a simple 'update' operation with 'map' can
be replaced with 'each' for Array, it looks like the implementation
of 'each' by the GA client doesn't have this behaviour (see below).

         .map(&method(:append_labels))
         .each { |h| h["date"] = date.strftime("%F") }
         .each_slice(batch_size) { |slice| yield slice }

     NoMethodError:
       undefined method `each_slice' for nil:NilClass